### ISSUE TITLE
Library uses PHP 5.4

### ISSUE THREAD

**Issue by JeroenDeDauw** [onoi/http-request#5]
It states it is compatible with PHP 5.3, yet uses PHP 5.4 features: https://github.com/onoi/http-request/blob/33dacf47e2c28c19e55ae631ec21dd9219ed663f/src/AsyncCurlRequest.php#L89 At least I think this does not work with 5.3. In any case, TravisCI is not testing the oldest supported PHP version.

**Comment by mwjames** [comment]
> It states it is compatible with PHP 5.3, yet uses PHP 5.4 features:

You mean `Closure`? This class exists since 5.3 according to [0].

>  TravisCI is not testing the oldest supported PHP version.

Good point.

[0] http://php.net/manual/de/class.closure.php

**Comment by mwjames** [comment]
PHP 5.3, https://github.com/onoi/http-request/commit/07b545701dfe099cd7a98da35bb3b009ae62abda
